# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

neighborhood <- function(m, m_nrow, m_ncol, w, m_i, m_j) {
    .Call(`_bmv_neighborhood`, m, m_nrow, m_ncol, w, m_i, m_j)
}

post_mean_x <- function(x, sigma, mu0, sigma0, nu) {
    .Call(`_bmv_post_mean_x`, x, sigma, mu0, sigma0, nu)
}

bayes_multiv_smooth <- function(m, m_nrow, m_ncol, w, sigma, nu, covar) {
    .Call(`_bmv_bayes_multiv_smooth`, m, m_nrow, m_ncol, w, sigma, nu, covar)
}

